#!/bin/sh
# Generate an archives file with markdown dated entries 

[ -z "$1" ] && echo "Must indicate valid directory" && exit 1

(echo "<h2>Archives</h2>"
cd "$1" && find . -iregex '.*\.md' -type f -exec awk '
BEGIN{ IGNORECASE=1; FS=":[[:space:]]*"} /^date:/{d=$2} /^title:/{t=$2} /^category:/{c=$2} END {if (d) print "<p>"d" | <a href=\""FILENAME"\" title=\""d"\">"t"</a> | Category: "c"</p>"}' {} \; | 
sed -r 's/(href=")\.(.*)\.md/\1\2\//i' | sort -r) > "$1/archives.html"

